### ISSUE TITLE
General Chat

### ISSUE THREAD

**Issue by nunodonato** [Kermer/GodotSteam#5]
Hi!
Sorry to comment here but couldn't find any other contact.
Are you still working on this? I'm going to integrate it in my godot game soon and would love to contribute back.

**Comment by Kermer** [comment]
I can say it's "on hold" right now. Want to get full access Steamworks to be able to test new features (like achievements) properly, but to do this I need to push some game through Greenlight first.

**Comment by nunodonato** [comment]
Oh! Let me know when you have one so I can vote ;)

So for what I understood, this is only available for Godot games built for Win or Linux. What happens if you build for mac?

**Comment by Kermer** [comment]
I never had any Mac in my hand, so I can't help much currently. In SDK's redistributable_bin folder there is library for osx32. So I guess if you add `elif env["platform"] == "osx"` (even unsure if "osx" is correct for SCons) in config.py and libpath you should be able to compile it.

**Comment by Gramps** [comment]
Kermer, I gutted and rebuilt your version of the project with the achievement and statistics stuff.  It all functions perfectly in my game.  I think you could pretty much pull those pieces from my version and put it in yours to compliment what you have already.

**Comment by Kermer** [comment]
@Gramps I thought they'll work fine, I just didn't have possibility to test it properly (no Steamworks access so I could only test it with Spacewar). Probably will update mine code in a few days then. I think I'm gonna make 2 objects: Steam and SteamUncommon (or something like that, some shorter name would be better) to store the functions like the ones you removed.
For example `set_server_info` will be useless for SP games, but can be quite useful for MP/coop games, since it can show the IP (and even more data if I could get the SteamGameServer to work) of the server you're playing on. Similar with `set_game_info`.

**Comment by Gramps** [comment]
Your Steam server functions were great.  Those are super useful.  A lot of what was in there is pretty good.  At first I wasn't sure what some of it was doing but a lot of the merged functions made sense when I really looked at them.

Originally I pulling over all the functions from the Steamworks API but then just rebuilt it to have all the functions I needed and, for me, a little clearer readability since I'm not a C programmer.

I'll keep an eye on your updates as you'll probably end up with more functionality than my version; hell, I think yours has more already.

Edit:  After my games launches on Steam I'll see what stuff is missing and try to add that in.
